version: '3.7'

networks:
  default:
    name: ${PROJECT}

volumes:
  dbdata:
    name: ${PROJECT}-postgres
  redis:
    name: ${PROJECT}-redis

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: stage
      args:
       UID: ${UID}
       GID: ${GID}
    container_name: ${PROJECT}-php
    # ports:
    #   - '8080:8080'
    volumes:
      - ./system/php:/var/www/log
      - ./htdocs:/var/www/project
    env_file:
      - .env.pgsql

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: ${PROJECT}-nginx
    volumes:
      - ./system/nginx:/var/log/nginx
      - ./htdocs:/var/www/project
    env_file:
      - .env.pgsql
    ports:
      - "${WEB_EXT_PORT}:80"

  redis:
    build:
      context: ./docker/redis
    container_name: ${PROJECT}-redis
    volumes:
      - ./redis:/data
    ports:
      - '6379:6379'

  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: ${PROJECT}-pgsql
    environment:
      - USERMAP_UID=${UID}
      - USERMAP_GID=${GID}
    ports:
      - '${POSTGRES_EXT_PORT}:5432'
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    env_file:
      - .env
      - .env.pgsql